[project]
name = "admin-lte-django-blog"
version = "0.1.0"
description = "django admin lte blog"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "crispy-bootstrap4>=2025.6",
  "django",
  "django-crispy-forms>=2.4",
  "requests>=2.32.5",
]
