# Generated by Django 5.2.7 on 2025-10-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_comment_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
